# Generated by Django 4.1.5 on 2023-01-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fishes')),
                ('name', models.CharField(max_length=220)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
